DROP DATABASE magiccraft_db;
CREATE DATABASE magiccraft_db;

USE magiccraft_db;

CREATE TABLE magic_craft_items(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	skill_rank VARCHAR(6),
	production_exp INT(15),
	materials VARCHAR(300),
    training_type VARCHAR(50)
);

INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Shyllien', 'N',	100,	'Shyllien Crystal × 5',	'Magic Conversion');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Training Mana Bullet', 'N',	150,	'Shyllien Crystal × 2',	'Mana Bullet Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Purified Rabbit Foot',	'D',	200,	'Shyllien × 1, Mutant Rabbit Foot × 1',	'Magic Material Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Mana Bullet',	'C',	250,	'Shyllien × 1',	'Mana Bullet Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Mysterious Herb Powder', 'C',	300,	'Bloody Herb × 1, Mana Herb × 1, Poison Herb × 1',	'Magic Material Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Sundew', 'B',	300,	'Shyllien × 1, Mutant Plant Mucilage × 1',	'Magic Material Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Enchanted Firewood', 'B',	1000,	'Shyllien × 1, Hillwen × 1, Average Firewood × 1',	'Magic Material Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Intact Shyllien', 'A',	1500,	'Shyllien × 1, Mysterious Herb Powder × 3',	'Magic Conversion');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ancient Magic Shyllien',  'A',	1500,	'Intact Shyllien × 1, Ancient Magic Crystal × 10',	'Magic Conversion');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('High-Density Mana Bullet', '9',	1000,	'Intact Shyllien × 1',	'Mana Bullet Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Lucky Rabbit Foot', '9',	2000,	'Purified Rabbit Foot × 5, Mysterious Herb Powder × 3, Intact Shyllien × 5',	'Magic Accessory Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Salvation Bow', '9',	4000,	'Mutant × 2, Apostle Ring × 2, Apostle Leather × 2, Apostles Sharpened Shard × 3, Apostles Hardened Shard × 4, Apostles Shining Shard × 8',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Original Sin Staff', '9',	4000,	'Mutant × 2, Apostle Ring × 2, Apostle Leather × 2, Apostles Shining Shard × 8, Apostles Hardened Shard × 6, Apostles Sharpened Shard × 2',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Gospel Cylinder', '9',	4000,	'Mutant × 2, Apostle Ring × 2, Apostle Leather × 3, Apostles Shining Shard × 6, Apostles Hardened Shard × 4, Apostles Sharpened Shard × 2',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Celtic Tribolt Wand', '9',	4000,	'Enchanted Firewood × 3, Intact Shyllien × 10, Mutant × 2, Broken Ring Frame x 2, Black Sealing Metal x 3, Forgotten Mages Gem x 6',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Celtic Druid Staff', '9',	4000,	'Enchanted Firewood × 3, Intact Shyllien × 20, Mutant × 2, Broken Ring Frame x 12, Black Sealing Metal x 3, Forgotten Mages Gem x 5',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Celtic Guardian Staff', '9',	4000,	'Enchanted Firewood × 3, Intact Shyllien × 20, Mutant × 2, Broken Ring Frame x 12, Black Sealing Metal x 8, Forgotten Mages Gem x 4',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Suntouched Mana Bullet', '8',	40000,	'Suntouched Shyllien Crystal × 1',	'Mana Bullet Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Blasted Oak Wand', '7',	2000,	'Enchanted Firewood × 1, Mysterious Herb Powder × 5, Intact Shyllien × 5',	'Magic Weapon or Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Languhiris Chaser Boots (M)', '7',	8000,	'Leather Shoes × 1, Intact Shyllien × 4, Mutant × 1, White Dragon Blood × 1, Dragon Scale × 3, Dragon Flesh Lump × 3',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Languhiris Chaser Boots (F)', '7',	8000,	'Leather Shoes × 1, Intact Shyllien × 4, Mutant × 1, White Dragon Blood × 1, Dragon Scale × 3, Dragon Flesh Lump × 3',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Languhiris Chaser Gloves', '7',	8000,	'Leather Gloves × 1, Intact Shyllien × 4, Mutant × 1, White Dragon Blood × 1, Dragon Scale × 3, Dragon Flesh Lump × 3',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Drosera', '7',	3000,	'Sundew × 5, Mysterious Herb Powder × 3, Intact Shyllien × 8',	'Magic Accessory Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Languhiris Chaser Circlet', '6',	10000,	'Intact Shyllien × 5Mutant × 1White Dragon Eyeball × 3White Dragon Blood × 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Mutant', '6',	2000,	'Mutant Rabbit Foot × 10, Mutant Plant Mucilage × 5, Sasquatch Heart × 3',	'Magic Material Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Enhanced Mutant', '6',	2000,	'Mutant × 1, Ancient Golden Crystal × 10',	'Magic Material Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Savage Fire Wand', '6', 6000,	'Enchanted Firewood × 3, Mysterious Herb Powder × 5, Intact Shyllien × 10, Mutant × 1, Fire Elemental × 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Savage Ice Wand', '6',	6000,	'Enchanted Firewood × 3, Mysterious Herb Powder × 5, Intact Shyllien × 10, Mutant × 1, Ice Elemental × 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Savage Lightning Wand', '6',	6000,	'Enchanted Firewood × 3, Mysterious Herb Powder × 5, Intact Shyllien × 10, Mutant × 1, Lightning Elemental × 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Languhiris Chaser Armor (M)', '5',	12000,	'Any Light Armor × 1, Intact Shyllien × 10, Mutant × 1, White Dragon Blood × 3, Dragon Scale × 5, Dragon Flesh Lump × 5',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Languhiris Chaser Armor (F)', '5',	12000,	'Any Light Armor × 1, Intact Shyllien × 10, Mutant × 1, White Dragon Blood × 3, Dragon Scale × 5, Dragon Flesh Lump × 5',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Hermits Staff', '5',	8000,	'Enchanted Firewood × 5, Mysterious Herb Powder × 5, Intact Shyllien × 20, Mutant × 1, Fire Elemental × 1, Lightning Elemental × 1, Ice Elemental × 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Purple Heart', '3',	5000,	'Sasquatch Heart × 1, Mysterious Herb Powder × 5, Intact Shyllien × 10',	'Magic Accessory Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Bhafel Hunter', '3',	10000,	'Long Bow × 1, Black Dragon Eyeball × 1, Black Dragon Blood × 5, Dragon Flesh Lump × 5, Intact Shyllien × 10, Mutant × 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Bhafel Huntress', '3',	8000,	'Arrow × 100, Intact Shyllien × 10, Mutant × 1, Black Dragon Heart × 1, Black Dragon Blood × 3','Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Languhiris Chaser', '3',	10000,	'Bear Knuckle × 1, Intact Shyllien × 10, Mutant × 1, White Dragon Heart × 1, White Dragon Blood × 3', 'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Altam Armor', '5', 12000,	'Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Armor x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Altam Gauntlets', '7',	8000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Gauntlets x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Altam Greaves', '7',	8000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Boots x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Avelin Armor', '5', 12000,	'Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Armor x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Avelin Gauntlets', '7',	8000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Gauntlets x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Avelin Greaves', '7',	8000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Boots x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Caswyns Armor', '5',	12000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Armor x 1', 'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Caswyns Gauntlets', '7',	8000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Gauntlets x 1', 'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Caswyns Greaves', '7',	8000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Boots x 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Llywelyn Armor', '5',	12000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Armor x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Llywelyn Gauntlets', '7', 8000,	'Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Gauntlets x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Llywelyn Greaves', '7',	8000,	'Ancient Magic Shyllien x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Boots x 1, Purified Soul Stone x 10', 'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Pihnes Armor', '5', 12000,	'Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Armor x 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Pihnes Gauntlets', '7',	8000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Gauntlets x 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Pihnes Greaves', '7',	8000,	'Ancient Magic Shyllien x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Boots x 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Talvish Armor', '5',	12000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Armor x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Talvish Gauntlets', '7', 8000,	'Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Gauntlets x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Improved Talvish Greaves', '7',	8000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Pure Metal Shard x 10, Medal of Courage x 5, Broken Guardians Boots x 1, Purified Soul Stone x 10',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Divine Tribolt Wand', '9',	4000,	'Ancient Magic Shyllien x 2, Enhanced Mutant x 2, Shining Metal Shard x 10, Medal of Wisdom x 5, Broken Guardians Wand x 1',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ladeca Blue Upgrade Stone', '3',	0,	'Blue Upgrade Stone × 5, Awakened Strength Powder × 5, Awakened Strength Fragment × 3, Awakened Strength Crystal × 1',	'?');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Eweca Red Upgrade Stone', '3',	0,	'Red Upgrade Stone × 5, Awakened Strength Powder × 5, Awakened Strength Fragment × 3, Awakened Strength Crystal × 1',	'?');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ancient Four-Leaf Clover Ornament', 'D1',	10000,	'Four-Leaf Clover × 1, Sundew x 5, Mysterious Herb Powder × 3, Intact Shyllien × 5, Suntouched Shyllien Crystal x 1',	'Magic Accessory Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ancient Horned Ring', 'D1',	10000,	'Enchanted Firewood × 3, Mysterious Herb Powder × 3, Intact Shyllien × 8, Suntouched Shyllien Crystal x 1',	'Magic Accessory Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ancient Sun Yeti Heart', 'D1',	10000,	'Sasquatch Heart × 1, Mysterious Herb Powder × 5, Intact Shyllien × 10, Suntouched Shyllien Crystal x 1',	'Magic Accessory Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Divine Spell Book', '9',	4000,	'Ancient Magic Shyllien × 2, Enhanced Mutant ×2, Shining Metal Shard × 10, Medal of Wisdom × 5, Broken Guardians Spell Book × 1, Sealed Divine Light Left Fragment × 1, Sealed Divine Light Right Fragment × 1', 'Magic Accessory Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Geas Devastation Chestplate (M)', '9',	25000,	'Eroded Mineral Chunk × 20, Geas Devastation Crystal × 16, Geas Core × 35, Finest Fabric × 10, Finest Silk × 10, Finest Leather × 10, Finest Leather Strap × 4, Intact Shyllien × 12, Mutant × 3',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Geas Devastation Chestplate (F)', '9',	25000,	'Eroded Mineral Chunk × 20, Geas Devastation Crystal × 16, Geas Core × 35, Finest Fabric × 10, Finest Silk × 10, Finest Leather × 10, Finest Leather Strap × 4, Intact Shyllien × 12, Mutant × 3',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Geas Devastation Boots (M)', '9',	25000,	'Battleworn Covering × 9, Geas Devastation Crystal × 9, Geas Core × 20, Finest Fabric × 3, Finest Silk × 3, Finest Leather × 3, Finest Leather Strap × 3, Intact Shyllien × 5, Mutant × 2',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Geas Devastation Boots (F)', '9',	25000,	'Battleworn Covering × 9, Geas Devastation Crystal × 9, Geas Core × 20, Finest Fabric × 3, Finest Silk × 3, Finest Leather × 3, Finest Leather Strap × 3, Intact Shyllien × 5, Mutant × 2',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Geas Devastation Gloves', '9',	25000,	'Leather Scrap × 9, Geas Devastation Crystal × 9, Geas Core × 30, Finest Fabric × 3, Finest Silk × 3, Finest Leather × 3, Finest Leather Strap × 3, Intact Shyllien × 6, Mutant × 2',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Geas Devastation Circlet', '9',	25000,	'Faded Fragment × 9, Geas Devastation Crystal × 3, Geas Core × 10, Finest Fabric × 3, Finest Silk × 3, Finest Leather × 3, Finest Leather Strap × 3, Intact Shyllien × 5, Mutant × 2', 'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ultimate Geas Devastation Chestplate (M)', '3',	25000,	'Geas Devastation Chestplate (M) × 1, Sharp Crystallized Mineral × 15, Geas Core × 65, Intact Shyllien × 12, Mutant × 3',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ultimate Geas Devastation Chestplate (F)', '3',	25000,	'Geas Devastation Chestplate (F) × 1, Sharp Crystallized Mineral × 15, Geas Core × 65, Intact Shyllien × 12, Mutant × 3',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ultimate Geas Devastation Boots (M)', '3',	25000,	'Geas Devastation Boots (M) × 1, Rift Hoof × 25, Geas Core × 45, Intact Shyllien × 5, Mutant × 2',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ultimate Geas Devastation Boots (F)', '3',	25000,	'Geas Devastation Boots (F) × 1, Rift Hoof × 25, Geas Core × 45, Intact Shyllien × 5, Mutant × 2',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ultimate Geas Devastation Gloves', '3',	25000,	'Geas Devastation Gloves × 1, Sturdy Leather Scrap × 25, Geas Core × 45, Intact Shyllien × 5, Mutant × 2',	'Magic Weapon and Armor Crafting');
INSERT INTO magic_craft_items (name, skill_rank, production_exp, materials, training_type) VALUES ('Ultimate Geas Devastation Circlet', '3',	25000,	'Geas Devastation Circlet × 1, Strange Shard × 25, Geas Core × 40, Intact Shyllien × 6, Mutant × 2',	'Magic Weapon and Armor Crafting');
